/* confdefs.h */
#define PACKAGE_NAME "weston"
#define PACKAGE_TARNAME "weston"
#define PACKAGE_VERSION "1.1.1"
#define PACKAGE_STRING "weston 1.1.1"
#define PACKAGE_BUGREPORT "https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=1.1.1"
#define PACKAGE_URL "http://wayland.freedesktop.org/"
#define PACKAGE "weston"
#define VERSION "1.1.1"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_EXECINFO_H 1
#define HAVE_MKOSTEMP 1
#define HAVE_STRCHRNUL 1
#define ENABLE_EGL 1
#define BUILD_XWAYLAND 1
#define HAVE_XCB_POLL_FOR_QUEUED_EVENT 1
#define BUILD_X11_COMPOSITOR 1
#define BUILD_DRM_COMPOSITOR 1
#define BUILD_WAYLAND_COMPOSITOR 1
#define BUILD_RPI_COMPOSITOR 1
#define BUILD_FBDEV_COMPOSITOR 1
#define BUILD_CLIENTS 1
#define HAVE_CAIRO_EGL 1
#define HAVE_SYSTEMD_LOGIN 1
#define BUILD_WCAP_TOOLS 1
#define WESTON_NATIVE_BACKEND "drm-backend.so"
